In [3]:
import pandas as pd

df = pd.read_csv("/srv/data1/general/immunopeptides_data/outputs/binding_score_function/1_processed_complexes/processed_pdbs.csv")

df.tail(10)

,Unnamed: 0.1,Unnamed: 0,pdb_code,resolution,release_year,binding_data,reference,ligand_name,peptide_sequence,protein_sequence,peptide_length
290,290,2800.0,6gvl,2.05,2019.0,Kd=44uM,6gvk.pdf,(30-mer),SNENLLLVHCGPTLINSCISFGS,VPDTPTRLVFSALGPTSLRVSWQEPRCPLQGYSVEYQLLNGGELHR...,23
291,291,2828.0,6jjw,2.40,2019.0,Kd=8.2nM,6jjw.pdf,(32-mer),IIVPSYRPTPDYETVMRQMK,LPLPEGWEEARDFDGKVYYIDHRNRTTSWIDPRDRYTKPLTFADCI...,20
292,292,2834.0,6jwj,1.58,2019.0,Kd=85.7nM,6jwj.pdf,(23-mer),MEPAKLDLPEGQLFFGFPM,SIKELAVDEELAAADGLIPRQKSKLCKHGDRGMCEYCSPLPPWDKE...,19
293,293,NaN,1ssc,NaN,NaN,Kd=35nM,NaN,NaN,PYVPVHFDASV,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,11
294,294,NaN,1ssc,NaN,NaN,Kd=19nM,NaN,NaN,RDIREISSRGAENING,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,16
295,295,NaN,1ssc,NaN,NaN,Kd=728nM,NaN,NaN,TARTIQKMDGHT,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,12
296,296,NaN,1ssc,NaN,NaN,Kd=4.34uM,NaN,NaN,GRYPREVERTENPGA,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,15
297,297,NaN,1ssc,NaN,NaN,Kd=7.18uM,NaN,NaN,EKIMKGMRSEGDTNESDHD,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,19
298,298,NaN,1ssc,NaN,NaN,Kd=7.54uM,NaN,NaN,GAKYPRACRSM,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,11
299,299,NaN,1ssc,NaN,NaN,Kd=7.93uM,NaN,NaN,GRELRPTCYPVGR,KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTF...,13

In [9]:
df = pd.read_csv("/srv/data1/general/immunopeptides_data/outputs/binding_score_function/3_scores/scores.csv")
df[df["complex_filename"].str.startswith("1ssc")]

,rosetta_score,interface_sasa,interface_dG,interface_delta_hbond_unsat,packstat,distance_score,iptm,peptide_plddt,peptide_pae,in_binding_site,...,turn_fraction,sheet_fraction,hydrophobic_aa_percent,polar_aa_percent,positively_charged_aa_percent,negatively_charged_aa_percent,delta_net_charge_frac,uHrel,complex_filename,is_decoy
293,-224.846222,1767.433979,-76.227400,1,0.754200,5.825247,0.92,94.220909,3.878219,True,...,0.363636,0.454545,54.545455,9.090909,9.090909,9.090909,0.000000,0.185060,1ssc_PYVPVHFDASV,False
294,-204.793318,2147.086492,-80.440826,7,0.709842,6.080036,0.90,88.531250,4.308447,True,...,0.437500,0.187500,25.000000,25.000000,18.750000,18.750000,0.000000,0.556023,1ssc_RDIREISSRGAENING,False
295,-201.152571,1962.176909,-76.546835,1,0.764741,5.806657,0.87,87.734167,5.918065,True,...,0.166667,0.333333,25.000000,33.333333,25.000000,8.333333,16.666667,0.449548,1ssc_TARTIQKMDGHT,False
296,-211.551672,2104.223742,-72.936172,3,0.698770,6.060348,0.87,88.873333,5.825066,True,...,0.333333,0.200000,20.000000,13.333333,20.000000,20.000000,0.000000,0.409401,1ssc_GRYPREVERTENPGA,False
297,-240.055481,2566.656903,-80.295218,20,0.759689,6.204664,0.88,86.694211,5.663025,True,...,0.421053,0.105263,15.789474,21.052632,21.052632,31.578947,-10.526316,0.292990,1ssc_EKIMKGMRSEGDTNESDHD,False
298,-203.056869,1846.362724,-61.766431,5,0.739204,6.024419,0.75,78.905455,8.049490,True,...,0.272727,0.090909,36.363636,18.181818,27.272727,0.000000,27.272727,0.420686,1ssc_GAKYPRACRSM,False
299,-189.239249,2333.206976,-73.424563,8,0.737897,5.754538,0.88,87.602308,6.240135,True,...,0.307692,0.307692,23.076923,15.384615,23.076923,7.692308,15.384615,0.671717,1ssc_GRELRPTCYPVGR,False